import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.compose.multiplatform)
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
}

// Point the real-document render test at a folder of actual PDFs:
//     ./gradlew :desktop:test -Dinkslate.pdfs="C:/Users/me/Documents"
// Gradle keeps a -D to itself, so it has to be handed on to the tests deliberately.
tasks.withType<Test>().configureEach {
    System.getProperty("inkslate.pdfs")?.let {
        systemProperty("inkslate.pdfs", it)
        // The documents behind it can change without anything here changing, and a sweep that
        // silently does not run is worse than no sweep - it reads as a pass.
        outputs.upToDateWhen { false }
    }
}

dependencies {
    // The document model, byte-for-byte the same classes the Android app uses.
    implementation(project(":core"))
    implementation(compose.desktop.currentOs)
    implementation(compose.material3)
    implementation(compose.materialIconsExtended)
    // Full Apache PDFBox on the desktop: unlike the Android port it can render pages itself.
    implementation(libs.pdfbox.jvm)
    // Reading the pen and the glass directly, because the runtime reports neither. See
    // WindowsPointer.kt - this is the whole reason the desktop build can tell a pen from a mouse.
    implementation(libs.jna)
    implementation(libs.jna.platform)

    testImplementation("junit:junit:4.13.2")
}

// The release workflow passes -Pinkslate.version, from the git tag and nowhere else.
val inkslateVersion = (findProperty("inkslate.version") as String? ?: "1.0.0")

/**
 * The version Windows Installer is told, which is not the version anybody reads.
 *
 * It insists on three numbers and compares only those, so "1.1.1-test.37" and "1.1.1-test.34"
 * both arrive as 1.1.1 - the same product at the same version - and installing one over the other
 * is not an upgrade at all. What Windows does instead is open the existing installation in
 * maintenance mode and verify every file of a bundled runtime against its cached copy before it
 * can offer anything, which is minutes of an empty window, and then it fails and falls back to
 * removing the product and installing it again.
 *
 * So the third number carries the test build as well as the patch: patch * 1000 + the build, and
 * a release takes 999 so that it always lands above every test build that led to it. The numbers
 * stay in order - 1.1.1037 then 1.1.1038 then the release at 1.1.1999, then 1.1.2000 for the next
 * patch's tests - which is the only property Windows actually uses. The version shown in the app
 * and on the release page is untouched; this is the one Windows keeps in Apps & Features.
 */
fun msiVersion(version: String): String {
    val core = version.split("-")[0].split(".").let { it + listOf("0", "0") }.take(3)
    val major = core[0].toIntOrNull() ?: 1
    val minor = core[1].toIntOrNull() ?: 0
    val patch = core[2].toIntOrNull() ?: 0

    // "1.1.1-test.37" -> 37, and anything unnumbered counts as a release.
    val build = Regex("""-test\.(\d+)""").find(version)?.groupValues?.get(1)?.toIntOrNull()

    // Windows allows 0-65535 here, so the patch cannot run past 65 before this needs rethinking.
    val third = (patch.coerceAtMost(65) * 1000) + (build?.coerceIn(0, 998) ?: 999)
    return "$major.$minor.$third"
}


compose.desktop {
    application {
        mainClass = "com.inkslate.desktop.MainKt"
        // Skiko loads its native renderer through System.load, which newer JDKs warn about on
        // every launch. The access is legitimate; this just stops the four-line warning.
        // The version is baked in beside it so the in-app update check compares against the
        // number this build was actually published under, rather than one written down twice.
        jvmArgs += listOf(
            "--enable-native-access=ALL-UNNAMED",
            "-Dinkslate.version=$inkslateVersion"
        )
        nativeDistributions {
            targetFormats(TargetFormat.Msi, TargetFormat.Exe)
            packageName = "InkSlate"
            packageVersion = msiVersion(inkslateVersion)

            windows {
                // The same mark the tablet's launcher icon is drawn from, generated by
                // brand/Brand.java. An app that looks like a different app depending on where you
                // meet it is two apps as far as anybody using it is concerned.
                iconFile.set(rootProject.file("brand/inkslate.ico"))

                // Without these, jpackage installs the program and leaves no way to start it:
                // no Start menu entry, nothing in search, no desktop icon offered. It was there
                // in Program Files and nowhere else.
                menu = true
                menuGroup = "InkSlate"
                shortcut = true

                // Offer the installation folder rather than deciding it silently.
                dirChooser = true

                // The code Windows uses to recognise one installation as the successor of
                // another, pinned to the value the installed copies already carry - read out of
                // the shipped 1.1.1 installer rather than invented. It has to be pinned because
                // the version below now changes with every test build, and jpackage derives this
                // code itself: if it turns out to derive it from the version too, each build
                // would install beside the last instead of replacing it. Pinning the existing
                // value is what keeps every copy already out there upgradeable.
                upgradeUuid = "A6D95BF2-0EA4-3BF8-AC13-05CC53EA1504"
            }
        }
    }
}

